### ISSUE TITLE
Noetic Playing Around Issues

### ISSUE THREAD

**Issue by AdamPettinger** [PaperFanz/insitu#10]
Found a few things:

- After added a new mode, there is a `Add View` button, but that button doesn't do anything
- Running just `insitu` there are no topics to view... but I can still add views and filters (once it Seg faulted after doing so)

**Comment by PaperFanz** [comment]
Pushed a fix, `Add View` button now properly opens the `Add View` Dialog. Views can no longer be created with an empty topic. I'll merge into `noetic` once the PR is tested and reviewed.
