### ISSUE TITLE
Instructions on default page

### ISSUE THREAD

**Issue by Daniel-Meza** [PaperFanz/insitu#21]
When running an insitu node (rosrun insitu insitu), it pops up with a blank page.
As a novice, I clicked around and crashed it.

Suggest instead of a blank page, we make it load a text file by default. This text file can have instructions/overview of how to use add modes -> views -> filter.

@PaperFanz @AdamPettinger

**Comment by Daniel-Meza** [comment]
Additionally, you might already be aware of this but:
- All options under menu "Help" don't do anything.
- Option "Preferences" under menu "Edit" does not do anything.

**Comment by PaperFanz** [comment]
Hi Daniel, thanks for your suggestion. I will definitely look into adding a tutorial page on startup, but the plan for now is to present a default "tutorial" task view using the included `Label` filter under `insitu_plugins`. The menu bar was populated as part of a default Qt project and I haven't gotten around to linking them up to anything, but it will be good to add it to an official to-do, thanks.

However, could you elaborate on how you were able to crash InSitu from the home screen?

**Comment by Daniel-Meza** [comment]
Sounds reasonable.

And sure, here are some ways I managed to crash it:
- Attempt to create a filter when there is no mode or view,
- Try to use notify filter. Did not crash but does throw error. For reference this is because the filter does not exist yet.
I'll keep you informed if I find others.
- Not sure what happened but the heartbeat filter crashed once or twice. But now it worked fine. I'll update if I find anything else on this.

Another thing to know:
- Once filter is created, an Edit button appears next to it. The only options for it are "Ok" and "Close".
