### ISSUE TITLE
lockToImageSize() bug

### ISSUE THREAD

**Issue by EAkita** [PaperFanz/insitu#23]
**Bug description**
Setting `lockToImageSize ()` to return "true" doesn't return the filter width() and height() in the `apply()` function

**To Reproduce**
1. Go to any filter.hpp file
2. Under public field in the class definition type:

`   bool lockToImageSize(void)
    {
        return true;
    }`
    
3.  Use width() or height() in the  `apply()` function. This returns 0. 
eg. `std::cout << width() <<std::endl; `

**Expected behavior**
`std::cout << width() <<std::endl; ` should return the correct root image width and height. 

 

**Desktop (please complete the following information):**
 - Ubuntu 20.04 
 - ROS Version: Noetic

**Comment by PaperFanz** [comment]
The bug should be resolved with the merging of #22. However, there is something that filter implementors should keep in mind.

Be sure to add `const` when reimplementing `hasSettingsEditor` and `lockToImageSize`. E.G.:
```
bool hasSettingsEditor(void) const { return true; }
bool lockToImageSize(void) const { return true; }
```

The filter creation templates have been updated to match this change.
