### ISSUE TITLE
Suggestion for adding multiple filters.

### ISSUE THREAD

**Issue by Daniel-Meza** [PaperFanz/insitu#30]
At the moment when you try to add a filter, the default name is "a_<filter>". This is always the case so when you add a second filter, if you don't change it then it throws an error saying there's already a module with that name.

Suggestion:
Should it update the default name to "b_<filter>", "c_<filter>", ... as you add more of the same type?
This seems like it should be a straightforward addition. Thoughts?

@PaperFanz @AdamPettinger 
P.S. I don't have permission to assign people to issues here on Github.

**Comment by PaperFanz** [comment]
@Daniel-Meza , thanks for the suggestion, but right now the prefix is the name of the view followed by an underscore. It would be straightforward to postfix the string with a number but that makes for an undescriptive differentiator. In my mind if you are choosing to add multiple of the same type of filter to the same view, then you should take the time to name them distinctly as well. If you feel that it's a necessary convenience, please fork the project and add the feature yourself and I will consider merging it into the project.

P.S. next time please use the issue templates to request a feature.
